---
title: "remap_interactive_rbp_scatter"
author: "juphilip"
date: "3/22/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
# libraries
rm(list = ls())
library(dplyr)
library(ggplot2)
library(stringr)
library(ggforce)
library(tidyr)
library(ggiraph)
library(kableExtra)
library(cowplot)
library(pheatmap)
library(tibble)
theme_set(theme_cowplot())

library(scales)


# load RBP funs
source("~/Documents/05_results/01_primates/andrew_pipeline/remap_01_2020/Draper_Philipp_et_al/RBP_filter_funs.R")

# load RNAcompete IDs
rnacmpt_ids <- read.delim("~/Documents/02_data/RNAcompete/rna_compete_ids.csv", sep = ",", stringsAsFactors = F, header = T) %>%
  filter(Species == "Homo_sapiens")
```

# Alternative first events
```{r event definitions, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
human_ASTC <- read.delim("~/Documents/05_results/01_primates/andrew_pipeline/remap_01_2020/astc_events/astc_events_human.txt",header = FALSE, stringsAsFactors = FALSE) %>% 
  filter(str_detect(V1, "AF"))

human_AS <- read.delim("~/Documents/05_results/01_primates/andrew_pipeline/remap_01_2020/as_events/as_events_human.txt", header = FALSE, stringsAsFactors = FALSE) %>% 
  filter(str_detect(V1, "AF"))

chimp_ASTC <- read.delim("~/Documents/05_results/01_primates/andrew_pipeline/remap_01_2020/astc_events/astc_events_chimp.txt", header = FALSE, stringsAsFactors = FALSE) %>% 
  filter(str_detect(V1,"AF"))

chimp_AS <- read.delim("~/Documents/05_results/01_primates/andrew_pipeline/remap_01_2020/as_events/as_events_chimp.txt", header = FALSE, stringsAsFactors = FALSE) %>% 
  filter(str_detect(V1,"AF"))

orang_ASTC <- read.delim("~/Documents/05_results/01_primates/andrew_pipeline/remap_01_2020/astc_events/astc_events_orang.txt", header = FALSE, stringsAsFactors = FALSE) %>% 
  filter(str_detect(V1,"AF"))

orang_AS <- read.delim("~/Documents/05_results/01_primates/andrew_pipeline/remap_01_2020/as_events/as_events_orang.txt", header = FALSE, stringsAsFactors = FALSE) %>% 
  filter(str_detect(V1, "AF"))
```

# load conserved vs not conserved lists
```{r load astc lists, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
load("~/Documents/05_results/01_primates/andrew_pipeline/remap_01_2020/cis_elements/march_21/astc_top_bottom_lists.RData")
```

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
attach('~/Documents/05_results/01_primates/andrew_pipeline/remap_01_2020/cis_elements/human_chimp_AF/hc_AF_ASTC_snp_lvl_prelim.RData', warn.conflicts = FALSE)

collapsed_output_total_score_human_chimp_AF <- collapsed_output_total_score

detach()

```

```{r load SNV background, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
attach("~/Documents/05_results/01_primates/andrew_pipeline/remap_01_2020/cis_elements/human_chimp_AF_AS/human_chimp_AF_AS_variant_calling_data_SNP_level.RData", warn.conflicts = FALSE)

collapsed_output_total_score_human_chimp_AF_SNV_bg <- collapsed_output_total_score

detach()
```

```{r load background, eval=FALSE, echo = FALSE, warning=FALSE, error=FALSE, message=FALSE}

load("~/Documents/05_results/01_primates/andrew_pipeline/remap_01_2020/cis_elements/march_21/summarized_rbp_bg.RData")
```



```{r human chimp AF NA replace, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
# events that are ASTC in human and AS in chimp
# NAs replaced with zero
data_a_hc_AF <- RBP_by_event_type(df=collapsed_output_total_score_human_chimp_AF,
                           species1="human",species2="chimp", species1_ASTC=human_ASTC,
                           species1_AS=human_AS, species1_event_type = "ASTC",
                           species2_ASTC=chimp_ASTC,species2_AS=chimp_AS, species2_event_type = "AS",
                           filter=FALSE, event_type="AF")

data_a_hc_AF_filtered <- RBP_by_event_type(df=collapsed_output_total_score_human_chimp_AF,
                           species1="human",species2="chimp", species1_ASTC=human_ASTC,
                           species1_AS=human_AS, species1_event_type = "ASTC",
                           species2_ASTC=chimp_ASTC,species2_AS=chimp_AS, species2_event_type = "AS",
                           filter=TRUE, event_type="AF")
 


# AS in human, ASTC in chimp
data_b_hc_AF <- RBP_by_event_type(df=collapsed_output_total_score_human_chimp_AF,
                        species1="human",species2="chimp", species1_ASTC=human_ASTC,
                        species1_AS=human_AS, species1_event_type = "AS",
                        species2_ASTC=chimp_ASTC,species2_AS=chimp_AS, species2_event_type = "ASTC",
                        filter=FALSE, event_type="AF")

data_b_hc_AF_filtered <- RBP_by_event_type(df=collapsed_output_total_score_human_chimp_AF,
                        species1="human",species2="chimp", species1_ASTC=human_ASTC,
                        species1_AS=human_AS, species1_event_type = "AS",
                        species2_ASTC=chimp_ASTC,species2_AS=chimp_AS, species2_event_type = "ASTC",
                        filter=TRUE, event_type="AF")


```

```{r human chimp AF ASTC NA replace, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
# events that are ASTC in both
data_c_hc_AF<- RBP_by_event_type(df=collapsed_output_total_score_human_chimp_AF,
                        species1="human",species2="chimp", species1_ASTC=human_ASTC,
                        species1_AS=human_AS, species1_event_type = "ASTC",
                        species2_ASTC=chimp_ASTC,species2_AS=chimp_AS, species2_event_type = "ASTC",
                        filter=FALSE, event_type="AF")

data_c_hc_AF_filtered <- RBP_by_event_type(df=collapsed_output_total_score_human_chimp_AF,
                        species1="human",species2="chimp", species1_ASTC=human_ASTC,
                        species1_AS=human_AS, species1_event_type = "ASTC",
                        species2_ASTC=chimp_ASTC,species2_AS=chimp_AS, species2_event_type = "ASTC",
                        filter=TRUE, event_type="AF")

```

```{r human chimp ASTC cons spec}
# events that are ASTC in both species (human and chimp) and have conserved sedimentation profiles
data_cons_hc_AF<- RBP_by_conservation(df=collapsed_output_total_score_human_chimp_AF,
                        species1="human",species2="chimp", conservation_df=astc_hc_AF_bottom,
                        conservation_status = "conserved",
                        filter=FALSE, event_type="AF")

data_cons_hc_AF_filtered <- RBP_by_conservation(df=collapsed_output_total_score_human_chimp_AF,
                        species1="human",species2="chimp", conservation_df=astc_hc_AF_bottom,
                        conservation_status = "conserved",
                        filter=TRUE, event_type="AF")

# events that are ASTC in both species (human and chimp) and have species-specific sedimentation profiles
data_spec_hc_AF<- RBP_by_conservation(df=collapsed_output_total_score_human_chimp_AF,
                        species1="human",species2="chimp", conservation_df=astc_hc_AF_top,
                        conservation_status = "species-specific",
                        filter=FALSE, event_type="AF")

data_spec_hc_AF_filtered<- RBP_by_conservation(df=collapsed_output_total_score_human_chimp_AF,
                        species1="human",species2="chimp", conservation_df=astc_hc_AF_top,
                        conservation_status = "species-specific",
                        filter=TRUE, event_type="AF")



```

```{r human chimp AF SNV background, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
data_d_hc_AF <- RBP_by_event_type(df=collapsed_output_total_score_human_chimp_AF_SNV_bg,
                           species1="human",species2="chimp", species1_ASTC=human_ASTC,
                           species1_AS=human_AS, species1_event_type = "AS",
                           species2_ASTC=chimp_ASTC,species2_AS=chimp_AS, species2_event_type = "AS",
                           filter=FALSE, event_type="AF")

data_d_hc_AF_filtered <- RBP_by_event_type(df=collapsed_output_total_score_human_chimp_AF_SNV_bg,
                           species1="human",species2="chimp", species1_ASTC=human_ASTC,
                           species1_AS=human_AS, species1_event_type = "AS",
                           species2_ASTC=chimp_ASTC,species2_AS=chimp_AS, species2_event_type = "AS",
                           filter=TRUE, event_type="AF")

```

```{r summary table}
rbp_table_long_hc_AF <- summary_table(rnacmpt_ids, data_a_hc_AF_filtered, data_b_hc_AF_filtered, data_c_hc_AF_filtered, data_d_hc_AF_filtered, data_cons_hc_AF_filtered, data_spec_hc_AF_filtered)
```


# human orang AF

## load data
```{r load human orang AF, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
attach("~/Documents/05_results/01_primates/andrew_pipeline/remap_01_2020/cis_elements/human_orang_AF/human_orang_AF_variant_calling_data_SNP_level.RData", warn.conflicts = FALSE)

collapsed_output_total_score_human_orang_AF <- collapsed_output_total_score

detach()
```

```{r load human orang AF SNV background, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
attach("~/Documents/05_results/01_primates/andrew_pipeline/remap_01_2020/cis_elements/human_orang_AF_AS/human_orang_AF_AS_variant_calling_data_SNP_level.RData", warn.conflicts = FALSE)

collapsed_output_total_score_human_orang_AF_SNV_bg <- collapsed_output_total_score

detach()
```

## sort data
```{r human orang AF NA replace, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

data_a_ho_AF <- RBP_by_event_type(df=collapsed_output_total_score_human_orang_AF,
                           species1="human",species2="orang", species1_ASTC=human_ASTC,
                           species1_AS=human_AS, species1_event_type = "ASTC",
                           species2_ASTC=orang_ASTC,species2_AS=orang_AS, species2_event_type = "AS",
                           filter=FALSE, event_type="AF")

data_a_ho_AF_filtered <- RBP_by_event_type(df=collapsed_output_total_score_human_orang_AF,
                           species1="human",species2="orang", species1_ASTC=human_ASTC,
                           species1_AS=human_AS, species1_event_type = "ASTC",
                           species2_ASTC=orang_ASTC,species2_AS=orang_AS, species2_event_type = "AS",
                           filter=TRUE, event_type="AF")

data_b_ho_AF <- RBP_by_event_type(df=collapsed_output_total_score_human_orang_AF,
                           species1="human",species2="orang", species1_ASTC=human_ASTC,
                           species1_AS=human_AS, species1_event_type = "AS",
                           species2_ASTC=orang_ASTC,species2_AS=orang_AS, species2_event_type = "ASTC",
                           filter=FALSE, event_type="AF")

data_b_ho_AF_filtered <- RBP_by_event_type(df=collapsed_output_total_score_human_orang_AF,
                           species1="human",species2="orang", species1_ASTC=human_ASTC,
                           species1_AS=human_AS, species1_event_type = "AS",
                           species2_ASTC=orang_ASTC,species2_AS=orang_AS, species2_event_type = "ASTC",
                           filter=TRUE, event_type="AF")



```

```{r human orang ASTC AF NA replace, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

data_c_ho_AF <- RBP_by_event_type(df=collapsed_output_total_score_human_orang_AF,
                           species1="human",species2="orang", species1_ASTC=human_ASTC,
                           species1_AS=human_AS, species1_event_type = "ASTC",
                           species2_ASTC=orang_ASTC,species2_AS=orang_AS, species2_event_type = "ASTC",
                           filter=FALSE, event_type="AF")

data_c_ho_AF_filtered <- RBP_by_event_type(df=collapsed_output_total_score_human_orang_AF,
                           species1="human",species2="orang", species1_ASTC=human_ASTC,
                           species1_AS=human_AS, species1_event_type = "ASTC",
                           species2_ASTC=orang_ASTC,species2_AS=orang_AS, species2_event_type = "ASTC",
                           filter=TRUE, event_type="AF")

```

```{r human orang ASTC cons vs spec, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
data_cons_ho_AF<- RBP_by_conservation(df=collapsed_output_total_score_human_orang_AF,
                        species1="human",species2="orang", conservation_df=astc_ho_AF_bottom,
                        conservation_status = "conserved",
                        filter=FALSE, event_type="AF")

data_cons_ho_AF_filtered<- RBP_by_conservation(df=collapsed_output_total_score_human_orang_AF,
                        species1="human",species2="orang", conservation_df=astc_ho_AF_bottom,
                        conservation_status = "conserved",
                        filter=TRUE, event_type="AF")



data_spec_ho_AF<- RBP_by_conservation(df=collapsed_output_total_score_human_orang_AF,
                        species1="human",species2="orang", conservation_df=astc_ho_AF_top,
                        conservation_status = "species-specific",
                        filter=FALSE, event_type="AF")

data_spec_ho_AF_filtered<- RBP_by_conservation(df=collapsed_output_total_score_human_orang_AF,
                        species1="human",species2="orang", conservation_df=astc_ho_AF_top,
                        conservation_status = "species-specific",
                        filter=TRUE, event_type="AF")
 
```

```{r human orang AF SNV background, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
data_d_ho_AF <- RBP_by_event_type(df=collapsed_output_total_score_human_orang_AF_SNV_bg,
                           species1="human",species2="orang", species1_ASTC=human_ASTC,
                           species1_AS=human_AS, species1_event_type = "AS",
                           species2_ASTC=orang_ASTC,species2_AS=orang_AS, species2_event_type = "AS",
                           filter=FALSE, event_type="AF")

data_d_ho_AF_filtered <- RBP_by_event_type(df=collapsed_output_total_score_human_orang_AF_SNV_bg,
                           species1="human",species2="orang", species1_ASTC=human_ASTC,
                           species1_AS=human_AS, species1_event_type = "AS",
                           species2_ASTC=orang_ASTC,species2_AS=orang_AS, species2_event_type = "AS",
                           filter=TRUE, event_type="AF")

```

```{r summary table}
rbp_table_long_ho_AF <- summary_table(rnacmpt_ids, data_a_ho_AF_filtered, data_b_ho_AF_filtered, data_c_ho_AF_filtered, data_d_ho_AF_filtered, data_cons_ho_AF_filtered, data_spec_ho_AF_filtered)
```


# skipped exon events

## load event definitions
```{r event definitions SE, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
human_ASTC <- read.delim("~/Documents/05_results/01_primates/andrew_pipeline/remap_01_2020/astc_events/astc_events_human.txt",header = FALSE, stringsAsFactors = FALSE) %>% 
  filter(str_detect(V1, "SE"))

human_AS <- read.delim("~/Documents/05_results/01_primates/andrew_pipeline/remap_01_2020/as_events/as_events_human.txt", header = FALSE, stringsAsFactors = FALSE) %>% 
  filter(str_detect(V1, "SE"))

chimp_ASTC <- read.delim("~/Documents/05_results/01_primates/andrew_pipeline/remap_01_2020/astc_events/astc_events_chimp.txt", header = FALSE, stringsAsFactors = FALSE) %>% 
  filter(str_detect(V1,"SE"))

chimp_AS <- read.delim("~/Documents/05_results/01_primates/andrew_pipeline/remap_01_2020/as_events/as_events_chimp.txt", header = FALSE, stringsAsFactors = FALSE) %>% 
  filter(str_detect(V1,"SE"))

orang_ASTC <- read.delim("~/Documents/05_results/01_primates/andrew_pipeline/remap_01_2020/astc_events/astc_events_orang.txt", header = FALSE, stringsAsFactors = FALSE) %>% 
  filter(str_detect(V1,"SE"))

orang_AS <- read.delim("~/Documents/05_results/01_primates/andrew_pipeline/remap_01_2020/as_events/as_events_orang.txt", header = FALSE, stringsAsFactors = FALSE) %>% 
  filter(str_detect(V1, "SE"))
```

## human/chimp

## load data
```{r,  echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
attach("~/Documents/05_results/01_primates/andrew_pipeline/remap_01_2020/cis_elements/human_chimp_SE/human_chimp_SE_variant_calling_data_SNP_level.RData", warn.conflicts = FALSE)

collapsed_output_total_score_human_chimp_SE <- collapsed_output_total_score

detach()
```

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
attach("~/Documents/05_results/01_primates/andrew_pipeline/remap_01_2020/cis_elements/human_chimp_SE_AS/human_chimp_SE_AS_variant_calling_data_SNP_level.RData", warn.conflicts = FALSE)

collapsed_output_total_score_human_chimp_SE_SNV_bg <- collapsed_output_total_score

detach()
```

## sort data

```{r human chimp SE NA replace,  echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
data_a_hc_SE <- RBP_by_event_type(df=collapsed_output_total_score_human_chimp_SE,
                           species1="human",species2="chimp", species1_ASTC=human_ASTC,
                           species1_AS=human_AS, species1_event_type = "ASTC",
                           species2_ASTC=chimp_ASTC,species2_AS=chimp_AS, species2_event_type = "AS",
                           filter=FALSE, event_type="SE")

data_a_hc_SE_filtered <- RBP_by_event_type(df=collapsed_output_total_score_human_chimp_SE,
                           species1="human",species2="chimp", species1_ASTC=human_ASTC,
                           species1_AS=human_AS, species1_event_type = "ASTC",
                           species2_ASTC=chimp_ASTC,species2_AS=chimp_AS, species2_event_type = "AS",
                           filter=TRUE, event_type="SE")


data_b_hc_SE <- RBP_by_event_type(df=collapsed_output_total_score_human_chimp_SE,
                           species1="human",species2="chimp", species1_ASTC=human_ASTC,
                           species1_AS=human_AS, species1_event_type = "AS",
                           species2_ASTC=chimp_ASTC,species2_AS=chimp_AS, species2_event_type = "ASTC",
                           filter=FALSE, event_type="SE")

data_b_hc_SE_filtered <- RBP_by_event_type(df=collapsed_output_total_score_human_chimp_SE,
                           species1="human",species2="chimp", species1_ASTC=human_ASTC,
                           species1_AS=human_AS, species1_event_type = "AS",
                           species2_ASTC=chimp_ASTC,species2_AS=chimp_AS, species2_event_type = "ASTC",
                           filter=TRUE, event_type="SE")


```

```{r human chimp ASTC SE NA replace, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

data_c_hc_SE <- RBP_by_event_type(df=collapsed_output_total_score_human_chimp_SE,
                           species1="human",species2="chimp", species1_ASTC=human_ASTC,
                           species1_AS=human_AS, species1_event_type = "ASTC",
                           species2_ASTC=chimp_ASTC,species2_AS=chimp_AS, species2_event_type = "ASTC",
                           filter=FALSE, event_type="SE")

data_c_hc_SE_filtered <- RBP_by_event_type(df=collapsed_output_total_score_human_chimp_SE,
                           species1="human",species2="chimp", species1_ASTC=human_ASTC,
                           species1_AS=human_AS, species1_event_type = "ASTC",
                           species2_ASTC=chimp_ASTC,species2_AS=chimp_AS, species2_event_type = "ASTC",
                           filter=TRUE, event_type="SE")

```

```{r human chimp ASTC SE cons spec, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
data_cons_hc_SE<- RBP_by_conservation(df=collapsed_output_total_score_human_chimp_SE,
                        species1="human",species2="chimp", conservation_df=astc_hc_SE_bottom,
                        conservation_status = "conserved",
                        filter=FALSE, event_type="SE")

data_cons_hc_SE_filtered<- RBP_by_conservation(df=collapsed_output_total_score_human_chimp_SE,
                        species1="human",species2="chimp", conservation_df=astc_hc_SE_bottom,
                        conservation_status = "conserved",
                        filter=TRUE, event_type="SE")



data_spec_hc_SE<- RBP_by_conservation(df=collapsed_output_total_score_human_chimp_SE,
                        species1="human",species2="chimp", conservation_df=astc_hc_SE_top,
                        conservation_status = "species-specific",
                        filter=FALSE, event_type="SE")

data_spec_hc_SE_filtered <- RBP_by_conservation(df=collapsed_output_total_score_human_chimp_SE,
                        species1="human",species2="chimp", conservation_df=astc_hc_SE_top,
                        conservation_status = "species-specific",
                        filter=TRUE, event_type="SE")

```

```{r human chimp SE SNV background, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
data_d_hc_SE <- RBP_by_event_type(df=collapsed_output_total_score_human_chimp_SE_SNV_bg,
                           species1="human",species2="chimp", species1_ASTC=human_ASTC,
                           species1_AS=human_AS, species1_event_type = "AS",
                           species2_ASTC=chimp_ASTC,species2_AS=chimp_AS, species2_event_type = "AS",
                           filter=FALSE, event_type="SE")

data_d_hc_SE_filtered <- RBP_by_event_type(df=collapsed_output_total_score_human_chimp_SE_SNV_bg,
                           species1="human",species2="chimp", species1_ASTC=human_ASTC,
                           species1_AS=human_AS, species1_event_type = "AS",
                           species2_ASTC=chimp_ASTC,species2_AS=chimp_AS, species2_event_type = "AS",
                           filter=TRUE, event_type="SE")

```

```{r summary table}
rbp_table_long_hc_SE <- summary_table(rnacmpt_ids, data_a_hc_SE_filtered, data_b_hc_SE_filtered, data_c_hc_SE_filtered, data_d_hc_SE_filtered, data_cons_hc_SE_filtered, data_spec_hc_SE_filtered)
```


## human/orang

## load data
```{r,  echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
attach("~/Documents/05_results/01_primates/andrew_pipeline/remap_01_2020/cis_elements/human_orang_SE/human_orang_SE_variant_calling_data_SNP_level.RData", warn.conflicts = FALSE)

collapsed_output_total_score_human_orang_SE <- collapsed_output_total_score

detach()
```

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
attach("~/Documents/05_results/01_primates/andrew_pipeline/remap_01_2020/cis_elements/human_orang_SE_AS/human_orang_SE_AS_variant_calling_data_SNP_level.RData", warn.conflicts = FALSE)

collapsed_output_total_score_human_orang_SE_SNV_bg <- collapsed_output_total_score

detach()
```

## sort data
```{r human orang SE NA replace , echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

data_a_ho_SE <- RBP_by_event_type(df=collapsed_output_total_score_human_orang_SE,
                           species1="human",species2="orang", species1_ASTC=human_ASTC,
                           species1_AS=human_AS, species1_event_type = "ASTC",
                           species2_ASTC=orang_ASTC,species2_AS=orang_AS, species2_event_type = "AS",
                           filter=FALSE, event_type="SE")

data_a_ho_SE_filtered <- RBP_by_event_type(df=collapsed_output_total_score_human_orang_SE,
                           species1="human",species2="orang", species1_ASTC=human_ASTC,
                           species1_AS=human_AS, species1_event_type = "ASTC",
                           species2_ASTC=orang_ASTC,species2_AS=orang_AS, species2_event_type = "AS",
                           filter=TRUE, event_type="SE")


data_b_ho_SE <- RBP_by_event_type(df=collapsed_output_total_score_human_orang_SE,
                           species1="human",species2="orang", species1_ASTC=human_ASTC,
                           species1_AS=human_AS, species1_event_type = "AS",
                           species2_ASTC=orang_ASTC,species2_AS=orang_AS, species2_event_type = "ASTC",
                           filter=FALSE, event_type="SE")

data_b_ho_SE_filtered <- RBP_by_event_type(df=collapsed_output_total_score_human_orang_SE,
                           species1="human",species2="orang", species1_ASTC=human_ASTC,
                           species1_AS=human_AS, species1_event_type = "AS",
                           species2_ASTC=orang_ASTC,species2_AS=orang_AS, species2_event_type = "ASTC",
                           filter=TRUE, event_type="SE")

```

```{r human orang ASTC SE NA replace, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

data_c_ho_SE <- RBP_by_event_type(df=collapsed_output_total_score_human_orang_SE,
                           species1="human",species2="orang", species1_ASTC=human_ASTC,
                           species1_AS=human_AS, species1_event_type = "ASTC",
                           species2_ASTC=orang_ASTC,species2_AS=orang_AS, species2_event_type = "ASTC",
                           filter=FALSE, event_type="SE")

data_c_ho_SE_filtered <- RBP_by_event_type(df=collapsed_output_total_score_human_orang_SE,
                           species1="human",species2="orang", species1_ASTC=human_ASTC,
                           species1_AS=human_AS, species1_event_type = "ASTC",
                           species2_ASTC=orang_ASTC,species2_AS=orang_AS, species2_event_type = "ASTC",
                           filter=TRUE, event_type="SE")

```

```{r human orang ASTC SE cons vs spec, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
data_cons_ho_SE<- RBP_by_conservation(df=collapsed_output_total_score_human_orang_SE,
                        species1="human",species2="orang", conservation_df=astc_ho_SE_bottom,
                        conservation_status = "conserved",
                        filter=FALSE, event_type="SE")

data_cons_ho_SE_filtered <- RBP_by_conservation(df=collapsed_output_total_score_human_orang_SE,
                        species1="human",species2="orang", conservation_df=astc_ho_SE_bottom,
                        conservation_status = "conserved",
                        filter=TRUE, event_type="SE")


data_spec_ho_SE<- RBP_by_conservation(df=collapsed_output_total_score_human_orang_SE,
                        species1="human",species2="orang", conservation_df=astc_ho_SE_top,
                        conservation_status = "species-specific",
                        filter=FALSE, event_type="SE")

data_spec_ho_SE_filtered<- RBP_by_conservation(df=collapsed_output_total_score_human_orang_SE,
                        species1="human",species2="orang", conservation_df=astc_ho_SE_top,
                        conservation_status = "species-specific",
                        filter=TRUE, event_type="SE")



```

```{r human orang SE SNV background, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

data_d_ho_SE <- RBP_by_event_type(df=collapsed_output_total_score_human_orang_SE_SNV_bg,
                           species1="human",species2="orang", species1_ASTC=human_ASTC,
                           species1_AS=human_AS, species1_event_type = "AS",
                           species2_ASTC=orang_ASTC,species2_AS=orang_AS, species2_event_type = "AS",
                           filter=FALSE, event_type="SE")

data_d_ho_SE_filtered <- RBP_by_event_type(df=collapsed_output_total_score_human_orang_SE_SNV_bg,
                           species1="human",species2="orang", species1_ASTC=human_ASTC,
                           species1_AS=human_AS, species1_event_type = "AS",
                           species2_ASTC=orang_ASTC,species2_AS=orang_AS, species2_event_type = "AS",
                           filter=TRUE, event_type="SE")

```

```{r summary table}
rbp_table_long_ho_SE <- summary_table(rnacmpt_ids, data_a_ho_SE_filtered, data_b_ho_SE_filtered, data_c_ho_SE_filtered, data_d_ho_SE_filtered, data_cons_ho_SE_filtered, data_spec_ho_SE_filtered)
```


## add significance based on prop test
```{r add significance levels to final data a tables, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
data_a_list <- list(data_a_hc_AF, data_a_ho_AF, data_a_hc_SE, data_a_ho_SE)
data_b_list <- list(data_b_hc_AF, data_b_ho_AF, data_b_hc_SE, data_b_ho_SE)
data_c_list <- list(data_c_hc_AF, data_c_ho_AF, data_c_hc_SE, data_c_ho_SE)
data_d_list <- list(data_d_hc_AF, data_d_ho_AF, data_d_hc_SE, data_d_ho_SE)
data_cons_list <- list(data_cons_hc_AF, data_cons_ho_AF, data_cons_hc_SE, data_cons_ho_SE)
data_spec_list <- list(data_spec_hc_AF, data_spec_ho_AF, data_spec_hc_SE, data_spec_ho_SE)

rbp_list <- list(rbp_table_long_hc_AF, rbp_table_long_ho_AF, rbp_table_long_hc_SE, rbp_table_long_ho_SE)


# mode total = using AS_ASTC_total for frequency/sig
data_a_sig <- mapply(add_sig_level, data_a_list, rbp_list, mode="total", SIMPLIFY = FALSE)
data_b_sig <- mapply(add_sig_level, data_b_list, rbp_list, mode="total", SIMPLIFY = FALSE)
data_c_sig <- mapply(add_sig_level, data_c_list, rbp_list, mode="total", SIMPLIFY = FALSE)
data_d_sig <- mapply(add_sig_level, data_d_list, rbp_list, mode="total", SIMPLIFY = FALSE)
data_cons_sig <- mapply(add_sig_level, data_cons_list, mode="total", rbp_list, SIMPLIFY = FALSE)
data_spec_sig <- mapply(add_sig_level, data_spec_list, mode="total", rbp_list, SIMPLIFY = FALSE)

# add signifcance levels from comparison of h_ASTC_c_AS to AS_AS, not the AS_ASTC_total
data_a_ind_sig <- mapply(add_sig_level, data_a_list, rbp_list, mode="AS_ASTC", SIMPLIFY = FALSE)

# add signifcance levels from comparison of h_AS_c_ASTCto AS_AS, not the AS_ASTC_total
data_b_ind_sig <- mapply(add_sig_level, data_b_list, rbp_list, mode="ASTC_AS", SIMPLIFY = FALSE)

```



# all comparisons and event types into one plot
```{r combine all observations, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
data_a_combined <- do.call(rbind, data_a_sig)

data_b_combined <- do.call(rbind, data_b_sig)

data_c_combined <- do.call(rbind, data_c_sig)

data_d_combined <- do.call(rbind, data_c_sig)

data_cons_combined <- do.call(rbind, data_cons_sig)

data_spec_combined <- do.call(rbind, data_spec_sig)

data_a_ind_combined <- do.call(rbind, data_a_ind_sig)
  
data_b_ind_combined <- do.call(rbind, data_b_ind_sig)


```

```{r turn data into heatmap, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
# with frequency in cell but only if it's significant
# collecting data columns
# essentially four heatmaps for human/chimp AF, human/chimp SE, human/orang AF, human/orang SE

col_0 <- table_0 %>% 
  select(Var1)
colnames(col_0)[1] <- "current_motif"

# AS ASTC total AF hc
colA <- data_a_combined[which(data_a_combined$event_type == "AF" & data_a_combined$species == "human_chimp"),c("current_motif","chisq","frequency","sig")] %>% 
  rbind(data_b_combined[which(data_b_combined$event_type == "AF" & data_b_combined$species == "human_chimp"),c("current_motif","chisq","frequency","sig")])%>%  
  unique() %>% 
  mutate(freq = case_when(!is.na(sig) ~ frequency)) %>% 
  unique() %>% 
  select(current_motif, freq)

# hASTC/cAS
colB <- data_a_ind_combined[which(data_a_ind_combined$event_type == "AF" & data_a_ind_combined$species == "human_chimp"), c("current_motif","chisq", "frequency","sig")] %>% 
  unique() %>% 
  mutate(freq = case_when(!is.na(sig) ~ frequency)) %>% 
  unique() %>% 
  select(current_motif, freq)

# hAS/cASTC
colC <- data_b_ind_combined[which(data_b_ind_combined$event_type == "AF" & data_b_ind_combined$species == "human_chimp"), c("current_motif","chisq", "frequency","sig")] %>% 
  unique() %>% 
  mutate(freq = case_when(!is.na(sig) ~ frequency)) %>% 
  unique() %>% 
  select(current_motif, freq)

# ASTC/ASTC hc AF
colD <- data_c_combined[which(data_c_combined$event_type == "AF" & data_c_combined$species == "human_chimp"), c("current_motif","chisq", "frequency","sig")] %>% 
  unique() %>% 
  mutate(freq = case_when(!is.na(sig) ~ frequency)) %>% 
  unique() %>% 
  select(current_motif, freq)

# conserved ASTC
colE <- data_cons_combined[which(data_cons_combined$event_type == "AF" & data_cons_combined$species == "human_chimp"), c("current_motif","chisq","frequency","sig")] %>% 
  unique() %>% 
  mutate(freq = case_when(!is.na(sig) ~ frequency)) %>% 
  unique() %>% 
  select(current_motif, freq)

# species specific ASTC
colF <- data_spec_combined[which(data_spec_combined$event_type == "AF" & data_spec_combined$species == "human_chimp"), c("current_motif","chisq","frequency","sig")] %>% 
  unique() %>% 
  mutate(freq = case_when(!is.na(sig) ~ frequency)) %>% 
  unique() %>% 
  select(current_motif, freq)

# hc AF background
colG <- data_d_combined[which(data_d_combined$event_type == "AF" & data_d_combined$species == "human_chimp"), c("current_motif","chisq","frequency","sig")] %>% 
  unique() %>% 
  mutate(freq = case_when(!is.na(sig) ~ frequency)) %>% 
  unique() %>% 
  select(current_motif, frequency)

# AS/ASTC hc SE
colH <- data_a_combined[which(data_a_combined$event_type == "SE" & data_a_combined$species == "human_chimp"), c("current_motif","chisq", "frequency","sig")] %>% 
  rbind(data_b_combined[which(data_b_combined$event_type == "SE" & data_b_combined$species == "human_chimp"), c("current_motif","chisq", "frequency","sig")]) %>%  
  unique() %>% 
  mutate(freq = case_when(!is.na(sig) ~ frequency)) %>% 
  unique() %>% 
  select(current_motif, freq)

# ASTC/ASTC hc SE
colI <- data_c_combined[which(data_c_combined$event_type == "SE" & data_c_combined$species == "human_chimp"), c("current_motif","chisq", "frequency","sig")] %>% 
  unique() %>% 
  mutate(freq = case_when(!is.na(sig) ~ frequency)) %>% 
  unique() %>% 
  select(current_motif, freq)

# hASTC/cAS SE
colJ <- data_a_ind_combined[which(data_a_ind_combined$event_type == "SE" & data_a_ind_combined$species == "human_chimp"), c("current_motif","chisq", "frequency","sig")] %>% 
  unique() %>% 
  mutate(freq = case_when(!is.na(sig) ~ frequency)) %>% 
  unique() %>% 
  select(current_motif, freq)

# hAS/cASTC SE
colK <- data_b_ind_combined[which(data_b_ind_combined$event_type == "SE" & data_b_ind_combined$species == "human_chimp"), c("current_motif","chisq", "frequency","sig")] %>% 
  unique() %>% 
  mutate(freq = case_when(!is.na(sig) ~ frequency)) %>% 
  unique() %>% 
  select(current_motif, freq)

# ASTC conserved hc SE
colL <- data_cons_combined[which(data_cons_combined$event_type == "SE" & data_cons_combined$species == "human_chimp"), c("current_motif","chisq","frequency","sig")] %>% 
  unique() %>% 
  mutate(freq = case_when(!is.na(sig) ~ frequency)) %>% 
  unique() %>% 
  select(current_motif, freq)

# species specific ASTC hc SE
colM <- data_spec_combined[which(data_spec_combined$event_type == "SE" & data_spec_combined$species == "human_chimp"), c("current_motif","chisq","frequency","sig")] %>% 
  unique() %>% 
  mutate(freq = case_when(!is.na(sig) ~ frequency)) %>% 
  unique() %>% 
  select(current_motif, freq)

# AS/AS SE hc background
colN <- data_d_combined[which(data_d_combined$event_type == "SE" & data_d_combined$species == "human_chimp"), c("current_motif","chisq","frequency","sig")] %>% 
  unique() %>% 
  mutate(freq = case_when(!is.na(sig) ~ frequency)) %>% 
  unique() %>% 
  select(current_motif, frequency)

# AS/ASTC ho AF

colO <- data_a_combined[which(data_a_combined$event_type == "AF" & data_a_combined$species == "human_orang"), c("current_motif","chisq", "frequency","sig")] %>% 
  rbind(data_b_combined[which(data_b_combined$event_type == "AF" & data_b_combined$species == "human_orang"), c("current_motif","chisq", "frequency","sig")]) %>%  
  unique() %>% 
  mutate(freq = case_when(!is.na(sig) ~ frequency)) %>% 
  unique() %>% 
  select(current_motif, freq)
  
# hASTC/oAS
colP <- data_a_ind_combined[which(data_a_ind_combined$event_type == "AF" & data_a_ind_combined$species == "human_orang"), c("current_motif","chisq", "frequency","sig")] %>% 
  unique() %>% 
  mutate(freq = case_when(!is.na(sig) ~ frequency)) %>% 
  unique() %>% 
  select(current_motif, freq)

# hAS/oASTC
colQ <- data_b_ind_combined[which(data_b_ind_combined$event_type == "AF" & data_b_ind_combined$species == "human_orang"), c("current_motif","chisq", "frequency","sig")] %>% 
  unique() %>% 
  mutate(freq = case_when(!is.na(sig) ~ frequency)) %>% 
  unique() %>% 
  select(current_motif, freq)

# ASTC/ASTC ho AF
colR <- data_c_combined[which(data_c_combined$event_type == "AF" & data_c_combined$species == "human_orang"), c("current_motif","chisq", "frequency","sig")] %>% 
  unique() %>% 
  mutate(freq = case_when(!is.na(sig) ~ frequency)) %>% 
  unique() %>% 
  select(current_motif, freq)

# ASTC conserved ho AF
colS <- data_cons_combined[which(data_cons_combined$event_type == "AF" & data_cons_combined$species == "human_orang"), c("current_motif","chisq","frequency","sig")] %>% 
  unique() %>% 
  mutate(freq = case_when(!is.na(sig) ~ frequency)) %>% 
  unique() %>% 
  select(current_motif, freq)

# species specific ASTC ho AF
colT <- data_spec_combined[which(data_spec_combined$event_type == "AF" & data_spec_combined$species == "human_orang"), c("current_motif","chisq","frequency","sig")] %>% 
  unique() %>% 
  mutate(freq = case_when(!is.na(sig) ~ frequency)) %>% 
  unique() %>% 
  select(current_motif, freq)

# backgorund ho AF
colU <- data_d_combined[which(data_d_combined$event_type == "AF" & data_d_combined$species == "human_orang"), c("current_motif","chisq","frequency","sig")] %>% 
  unique() %>% 
  mutate(freq = case_when(!is.na(sig) ~ frequency)) %>% 
  unique() %>% 
  select(current_motif, frequency)

# AS/ASTC ho SE
colV <- data_a_combined[which(data_a_combined$event_type == "SE" & data_a_combined$species == "human_orang"), c("current_motif","chisq", "frequency","sig")] %>% 
  rbind(data_b_combined[which(data_b_combined$event_type == "SE" & data_b_combined$species == "human_orang"), c("current_motif","chisq", "frequency","sig")]) %>%  
  unique() %>% 
  mutate(freq = case_when(!is.na(sig) ~ frequency)) %>% 
  unique() %>% 
  select(current_motif, freq)

# hASTC/oAS
colW <- data_a_ind_combined[which(data_a_ind_combined$event_type == "SE" & data_a_ind_combined$species == "human_orang"), c("current_motif","chisq", "frequency","sig")] %>% 
  unique() %>% 
  mutate(freq = case_when(!is.na(sig) ~ frequency)) %>% 
  unique() %>% 
  select(current_motif, freq)

# hAS/oASTC
colX <- data_b_ind_combined[which(data_b_ind_combined$event_type == "SE" & data_b_ind_combined$species == "human_orang"), c("current_motif","chisq", "frequency","sig")] %>% 
  unique() %>% 
  mutate(freq = case_when(!is.na(sig) ~ frequency)) %>% 
  unique() %>% 
  select(current_motif, freq)

# ASTC/ASTC ho SE
colY <- data_c_combined[which(data_c_combined$event_type == "SE" & data_c_combined$species == "human_orang"), c("current_motif","chisq", "frequency","sig")] %>% 
  unique() %>% 
  mutate(freq = case_when(!is.na(sig) ~ frequency)) %>% 
  unique() %>% 
  select(current_motif, freq)

# ASTC cons ho SE
colZ <- data_cons_combined[which(data_cons_combined$event_type == "SE" & data_cons_combined$species == "human_orang"), c("current_motif","chisq","frequency","sig")] %>% 
  unique() %>% 
  mutate(freq = case_when(!is.na(sig) ~ frequency)) %>% 
  unique() %>% 
  select(current_motif, freq)

# ASTC spec ho SE
colAA <- data_spec_combined[which(data_spec_combined$event_type == "SE" & data_spec_combined$species == "human_orang"), c("current_motif","chisq","frequency","sig")] %>% 
  unique() %>% 
  mutate(freq = case_when(!is.na(sig) ~ frequency)) %>% 
  unique() %>% 
  select(current_motif, freq)

# background ho SE
colBB <- data_d_combined[which(data_d_combined$event_type == "SE" & data_d_combined$species == "human_orang"), c("current_motif","chisq","frequency","sig")] %>% 
  unique() %>% 
  mutate(freq = case_when(!is.na(sig) ~ frequency)) %>% 
  unique() %>% 
  select(current_motif, frequency)

```


```{r bind norm log2, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
# bind columns together and normalize
test_heatmap_data_hc_AF <- col_0 %>% 
  left_join(colA, by = "current_motif") %>% 
  left_join(colB, by = "current_motif") %>% 
  left_join(colC, by = "current_motif") %>% 
  left_join(colD, by = "current_motif") %>% 
  left_join(colE, by = "current_motif") %>% 
  left_join(colF, by = "current_motif") %>% 
  left_join(colG, by = "current_motif") %>% 
  mutate(freq.x = log2(freq.x/frequency),
         freq.y = log2(freq.y/frequency),
         freq.x.x = log2(freq.x.x/frequency),
         freq.y.y = log2(freq.y.y/frequency),
         freq.x.x.x = log2(freq.x.x.x/frequency),
         freq.y.y.y = log2(freq.y.y.y/frequency)) %>% 
  mutate(frequency = log2(frequency/frequency)) %>% 
  column_to_rownames("current_motif")


test_heatmap_data_hc_SE <- col_0 %>% 
  left_join(colH, by = "current_motif") %>% 
  left_join(colI, by = "current_motif") %>% 
  left_join(colJ, by = "current_motif") %>% 
  left_join(colK, by = "current_motif") %>% 
  left_join(colL, by = "current_motif") %>% 
  left_join(colM, by = "current_motif") %>% 
  left_join(colN, by = "current_motif") %>% 
  mutate(freq.x = log2(freq.x/frequency),
         freq.y = log2(freq.y/frequency),
         freq.x.x = log2(freq.x.x/frequency),
         freq.y.y = log2(freq.y.y/frequency),
         freq.x.x.x = log2(freq.x.x.x/frequency),
         freq.y.y.y = log2(freq.y.y.y/frequency)) %>% 
  mutate(frequency = log2(frequency/frequency)) %>% 
  column_to_rownames("current_motif")

test_heatmap_data_ho_AF <- col_0 %>% 
  left_join(colO, by = "current_motif") %>% 
  left_join(colP, by = "current_motif") %>% 
  left_join(colQ, by = "current_motif") %>% 
  left_join(colR, by = "current_motif") %>% 
  left_join(colS, by = "current_motif") %>% 
  left_join(colT, by = "current_motif") %>% 
  left_join(colU, by = "current_motif") %>% 
  mutate(freq.x = log2(freq.x/frequency),
         freq.y = log2(freq.y/frequency),
         freq.x.x = log2(freq.x.x/frequency),
         freq.y.y = log2(freq.y.y/frequency),
         freq.x.x.x = log2(freq.x.x.x/frequency),
         freq.y.y.y = log2(freq.y.y.y/frequency)) %>% 
  mutate(frequency = log2(frequency/frequency)) %>% 
  column_to_rownames("current_motif")

test_heatmap_data_ho_SE <- col_0 %>% 
  left_join(colV, by = "current_motif") %>% 
  left_join(colW, by = "current_motif") %>% 
  left_join(colX, by = "current_motif") %>% 
  left_join(colY, by = "current_motif") %>% 
  left_join(colZ, by = "current_motif") %>% 
  left_join(colAA, by = "current_motif") %>% 
  left_join(colBB, by = "current_motif") %>% 
  mutate(freq.x = log2(freq.x/frequency),
         freq.y = log2(freq.y/frequency),
         freq.x.x = log2(freq.x.x/frequency),
         freq.y.y = log2(freq.y.y/frequency),
         freq.x.x.x = log2(freq.x.x.x/frequency),
         freq.y.y.y = log2(freq.y.y.y/frequency)) %>% 
  mutate(frequency = log2(frequency/frequency)) %>% 
  column_to_rownames("current_motif")

```

```{r heatmap annotation, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
hex_codes1 <- hue_pal()(80)
hex_codes2 <- hue_pal()(102)

rnacmpt_ids_sorted <- rnacmpt_ids %>% 
  arrange(ID)

heatmap_labels <- rnacmpt_ids_sorted %>% 
  mutate(PWM_RBP = paste0(Gene.name,"_",ID)) %>% 
  select(PWM_RBP, ID) %>% 
  column_to_rownames('ID')

annotation_colors <- hex_codes2
names(annotation_colors) <- heatmap_labels$PWM_RBP
annot_cols <- list(PWM_RBP = annotation_colors)
```


```{r for manuscript plotting heatmap normalize log2 in separate panels clust row false three columns only, echo = FALSE, warning=FALSE, message=FALSE}

# human/chimp AF

#filter out NA
test_heatmap_data_hc_AF_filtered <- test_heatmap_data_hc_AF %>% 
  select(c("freq.x","freq.y.y","frequency")) %>% 
  filter(!(is.na(freq.x) & is.na(freq.y.y)))

# replace inf
inf_df <- sapply(test_heatmap_data_hc_AF_filtered, is.infinite)
test_heatmap_data_hc_AF_filtered[inf_df] <- 0

colnames(test_heatmap_data_hc_AF_filtered) <- paste0("sample",1:ncol(test_heatmap_data_hc_AF_filtered))

col_labels <- c("AS_ASTC_total","ASTC_ASTC","AS_AS (ctrl)")

row_labels <- rnacmpt_ids_sorted_alpha[rnacmpt_ids_sorted_alpha$ID %in% rownames(test_heatmap_data_hc_AF_filtered),"Gene.name"]

pheatmap(test_heatmap_data_hc_AF_filtered, cluster_rows = FALSE, cluster_cols = FALSE, annotation_row = heatmap_labels, annotation_col = annot_rows, annotation_colors = annot_cols, labels_col = col_labels, labels_row = row_labels,
         cellwidth = 10,
         cellheight = 10,
         fontsize = 8,
         filename = "~/Documents/05_results/01_primates/andrew_pipeline/remap_01_2020/cis_elements/march_21/summary_heatmap_hc_AF_rowsort_3col.pdf"
         )


# human/chimp SE

#filter out NA
test_heatmap_data_hc_SE_filtered <- test_heatmap_data_hc_SE %>% 
  select(c("freq.x","freq.y.y","frequency")) %>% 
  filter(!(is.na(freq.x) & is.na(freq.y.y)))

# replace inf
inf_df <- sapply(test_heatmap_data_hc_SE_filtered, is.infinite)
test_heatmap_data_hc_SE_filtered[inf_df] <- 0

colnames(test_heatmap_data_hc_SE_filtered) <- paste0("sample",1:ncol(test_heatmap_data_hc_SE_filtered))

col_labels <- c("AS_ASTC_total","ASTC_ASTC","AS_AS (ctrl)")


row_labels <- rnacmpt_ids_sorted_alpha[rnacmpt_ids_sorted_alpha$ID %in% rownames(test_heatmap_data_hc_SE_filtered),"Gene.name"]
  
pheatmap(test_heatmap_data_hc_SE_filtered, cluster_rows = FALSE, cluster_cols = FALSE, annotation_row = heatmap_labels, annotation_col = annot_rows, annotation_colors = annot_cols, labels_col = col_labels, labels_row = row_labels, 
         cellwidth = 10,
         cellheight = 10,
         fontsize = 8,
         filename = "~/Documents/05_results/01_primates/andrew_pipeline/remap_01_2020/cis_elements/march_21/summary_heatmap_hc_SE_rowsort_3col.pdf"
         )

# human/orang AF
#filter out NA
test_heatmap_data_ho_AF_filtered <- test_heatmap_data_ho_AF %>% 
  select(c("freq.x","freq.y.y","frequency")) %>% 
  filter(!(is.na(freq.x) & is.na(freq.y.y)))

# replace inf
inf_df <- sapply(test_heatmap_data_ho_AF_filtered, is.infinite)
test_heatmap_data_ho_AF_filtered[inf_df] <- 0

colnames(test_heatmap_data_ho_AF_filtered) <- paste0("sample",1:ncol(test_heatmap_data_ho_AF_filtered))

col_labels <- c("AS_ASTC_total","ASTC_ASTC","AS_AS (ctrl)")


row_labels <- rnacmpt_ids_sorted_alpha[rnacmpt_ids_sorted_alpha$ID %in% rownames(test_heatmap_data_ho_AF_filtered),"Gene.name"]

pheatmap(test_heatmap_data_ho_AF_filtered, cluster_rows = FALSE, cluster_cols = FALSE, annotation_row = heatmap_labels, annotation_col = annot_rows, annotation_colors = annot_cols, labels_col = col_labels, labels_row = row_labels,
         cellwidth = 10,
         cellheight = 10,
         fontsize = 8,
         filename = "~/Documents/05_results/01_primates/andrew_pipeline/remap_01_2020/cis_elements/march_21/summary_heatmap_ho_AF_rowsort_3col.pdf")


# human/orang SE
#filter out NA
test_heatmap_data_ho_SE_filtered <- test_heatmap_data_ho_SE %>% 
  select(c("freq.x","freq.y.y","frequency")) %>% 
  filter(!(is.na(freq.x) & is.na(freq.y.y)))

# replace inf
inf_df <- sapply(test_heatmap_data_ho_SE_filtered, is.infinite)
test_heatmap_data_ho_SE_filtered[inf_df] <- 0


colnames(test_heatmap_data_ho_SE_filtered) <- paste0("sample",1:ncol(test_heatmap_data_ho_SE_filtered))

col_labels <- c("AS_ASTC_total","ASTC_ASTC","AS_AS (ctrl)")


row_labels <- rnacmpt_ids_sorted_alpha[rnacmpt_ids_sorted_alpha$ID %in% rownames(test_heatmap_data_ho_SE_filtered),"Gene.name"]
  
pheatmap(test_heatmap_data_ho_SE_filtered, cluster_rows = FALSE, cluster_cols = FALSE, annotation_row = heatmap_labels, annotation_col = annot_rows, annotation_colors = annot_cols, labels_col = col_labels, labels_row = row_labels, 
         cellwidth = 10,
         cellheight = 10,
         fontsize = 8,
         filename = "~/Documents/05_results/01_primates/andrew_pipeline/remap_01_2020/cis_elements/march_21/summary_heatmap_ho_SE_rowsort_3col.pdf")

```


```{r euler diagram of RBPs}
library(eulerr)
# human_chimp AF vs human_orang_AF
fit1 <- euler(c("human_chimp_AF" = length(rownames(test_heatmap_data_hc_AF_filtered)), 
                "human_orang_AF" = length(rownames(test_heatmap_data_ho_AF_filtered)), 
                "human_chimp_AF&human_orang_AF" = length(intersect(rownames(test_heatmap_data_ho_AF_filtered), rownames(test_heatmap_data_hc_AF_filtered)))))

pdf("~/Dropbox/JP/rbp/AF_RBP_overlap.pdf")
plot(fit1,
     quantities = TRUE)
dev.off()

# human_chimp SE vs human_orang SE

fit2 <- euler(c("human_chimp_SE" = length(rownames(test_heatmap_data_hc_SE_filtered)), 
                "human_orang_SE" = length(rownames(test_heatmap_data_ho_SE_filtered)), 
                "human_chimp_SE&human_orang_SE" = length(intersect(rownames(test_heatmap_data_ho_SE_filtered), rownames(test_heatmap_data_hc_SE_filtered)))))

pdf("~/Dropbox/JP/rbp/SE_RBP_overlap.pdf")
plot(fit2,
     quantities = TRUE)
dev.off()

# human chimp AF vs human chimp SE
fit3 <- euler(c("human_chimp_SE" = length(rownames(test_heatmap_data_hc_SE_filtered)), 
                "human_chimp_AF" = length(rownames(test_heatmap_data_hc_AF_filtered)), 
                "human_chimp_SE&human_chimp_AF" = length(intersect(rownames(test_heatmap_data_hc_SE_filtered), rownames(test_heatmap_data_hc_AF_filtered)))))

pdf("~/Dropbox/JP/rbp/human_chimp_overlap.pdf")
plot(fit3,
     quantities = TRUE)
dev.off()

# human orang AF vs human orang SE
fit4 <- euler(c("human_orang_SE" = length(rownames(test_heatmap_data_ho_SE_filtered)), 
                "human_orang_AF" = length(rownames(test_heatmap_data_ho_AF_filtered)), 
                "human_orang_SE&human_orang_AF" = length(intersect(rownames(test_heatmap_data_ho_SE_filtered), rownames(test_heatmap_data_ho_AF_filtered)))))

pdf("~/Dropbox/JP/rbp/human_orang_overlap.pdf")
plot(fit4,
     quantities = TRUE)
dev.off()
```

```{r euler diagrams for event ids}
fit1 <- euler(c("human_chimp_AF" = length(unique(collapsed_output_total_score_human_chimp_AF$event_id)), 
                "human_chimp_SE" = length(unique(collapsed_output_total_score_human_chimp_SE$event_id)), 
                "human_chimp_SE&human_chimp_AF" = length(intersect(unique(collapsed_output_total_score_human_chimp_AF$event_id),unique(collapsed_output_total_score_human_chimp_SE$event_id)))))


fit2 <- euler(c("human_chimp_AF" = length(unique(collapsed_output_total_score_human_chimp_AF$event_id)), 
                "human_orang_AF" = length(unique(collapsed_output_total_score_human_orang_AF$event_id)), 
                "human_chimp_AF&human_orang_AF" = length(intersect(unique(collapsed_output_total_score_human_chimp_AF$event_id),unique(collapsed_output_total_score_human_orang_AF$event_id)))))

pdf("~/Dropbox/JP/rbp/AF_event_overlap.pdf")
plot(fit2,
     quantities = TRUE)
dev.off()


fit3 <- euler(c("human_chimp_SE" = length(unique(collapsed_output_total_score_human_chimp_SE$event_id)), 
                "human_orang_SE" = length(unique(collapsed_output_total_score_human_orang_SE$event_id)), 
                "human_chimp_SE&human_orang_SE" = length(intersect(unique(collapsed_output_total_score_human_chimp_SE$event_id),unique(collapsed_output_total_score_human_orang_SE$event_id)))))

pdf("~/Dropbox/JP/rbp/SE_event_overlap.pdf")
plot(fit3,
     quantities = TRUE)
dev.off()


```

```{r euler diagram of RBPs based on 3col}
library(eulerr)
# human_chimp AF vs human_orang_AF
fit1 <- euler(c("human_chimp_AF" = length(rownames(test_heatmap_data_hc_AF_filtered)), 
                "human_orang_AF" = length(rownames(test_heatmap_data_ho_AF_filtered)), 
                "human_chimp_AF&human_orang_AF" = length(intersect(rownames(test_heatmap_data_ho_AF_filtered), rownames(test_heatmap_data_hc_AF_filtered)))))

pdf("~/Dropbox/JP/rbp/AF_RBP_overlap_3col.pdf")
plot(fit1,
     quantities = TRUE)
dev.off()

# human_chimp SE vs human_orang SE

fit2 <- euler(c("human_chimp_SE" = length(rownames(test_heatmap_data_hc_SE_filtered)), 
                "human_orang_SE" = length(rownames(test_heatmap_data_ho_SE_filtered)), 
                "human_chimp_SE&human_orang_SE" = length(intersect(rownames(test_heatmap_data_ho_SE_filtered), rownames(test_heatmap_data_hc_SE_filtered)))))

pdf("~/Dropbox/JP/rbp/SE_RBP_overlap_3col.pdf")
plot(fit2,
     quantities = TRUE)
dev.off()

# human chimp AF vs human chimp SE
fit3 <- euler(c("human_chimp_SE" = length(rownames(test_heatmap_data_hc_SE_filtered)), 
                "human_chimp_AF" = length(rownames(test_heatmap_data_hc_AF_filtered)), 
                "human_chimp_SE&human_chimp_AF" = length(intersect(rownames(test_heatmap_data_hc_SE_filtered), rownames(test_heatmap_data_hc_AF_filtered)))))

pdf("~/Dropbox/JP/rbp/human_chimp_overlap_3col.pdf")
plot(fit3,
     quantities = TRUE)
dev.off()

# human orang AF vs human orang SE
fit4 <- euler(c("human_orang_SE" = length(rownames(test_heatmap_data_ho_SE_filtered)), 
                "human_orang_AF" = length(rownames(test_heatmap_data_ho_AF_filtered)), 
                "human_orang_SE&human_orang_AF" = length(intersect(rownames(test_heatmap_data_ho_SE_filtered), rownames(test_heatmap_data_ho_AF_filtered)))))

pdf("~/Dropbox/JP/rbp/human_orang_overlap_3col.pdf")
plot(fit4,
     quantities = TRUE)
dev.off()
```

```{r euler diagrams for event ids newly filtered}
fit1 <- euler(c("human_chimp_AF" = length(unique(collapsed_output_total_score_human_chimp_AF$event_id)), 
                "human_chimp_SE" = length(unique(collapsed_output_total_score_human_chimp_SE$event_id)), 
                "human_chimp_SE&human_chimp_AF" = length(intersect(unique(collapsed_output_total_score_human_chimp_AF$event_id),unique(collapsed_output_total_score_human_chimp_SE$event_id)))))


fit2 <- euler(c("human_chimp_AF" = length(unique(collapsed_output_total_score_human_chimp_AF$event_id)), 
                "human_orang_AF" = length(unique(collapsed_output_total_score_human_orang_AF$event_id)), 
                "human_chimp_AF&human_orang_AF" = length(intersect(unique(collapsed_output_total_score_human_chimp_AF$event_id),unique(collapsed_output_total_score_human_orang_AF$event_id)))))

pdf("~/Dropbox/JP/rbp/AF_event_overlap_3col.pdf")
plot(fit2,
     quantities = TRUE)
dev.off()


fit3 <- euler(c("human_chimp_SE" = length(unique(collapsed_output_total_score_human_chimp_SE$event_id)), 
                "human_orang_SE" = length(unique(collapsed_output_total_score_human_orang_SE$event_id)), 
                "human_chimp_SE&human_orang_SE" = length(intersect(unique(collapsed_output_total_score_human_chimp_SE$event_id),unique(collapsed_output_total_score_human_orang_SE$event_id)))))

pdf("~/Dropbox/JP/rbp/SE_event_overlap_3col.pdf")
plot(fit3,
     quantities = TRUE)
dev.off()


```