---
title: "Remap_conservation_plots"
author: "juphilip"
date: "4/21/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
rm(list=ls(all=TRUE))
library(tidyverse)
library(ggplot2)
library(cowplot)

theme_set(theme_cowplot())

get_files <- function(x){
  tryCatch(read.delim(x, header = FALSE, stringsAsFactors = FALSE, sep = "\t"), error=function(e) NULL)}

```

```{r read in conservation score files}
all_phastcons <- read.delim("~/Documents/05_results/01_primates/andrew_pipeline/remap_01_2020/conservation/human_splice_site_regions_phastcons.tsv", header = FALSE, stringsAsFactors = FALSE) %>% 
  separate(V4, into = c("event_type", "SS", "event_id"), sep = ";")


```

```{r read in event lists}
all_species_distance <- read.delim("~/Documents/05_results/01_primates/andrew_pipeline/remap_01_2020/pipeline_output/human_chimp_orang/all_distances.tsv", header = TRUE, stringsAsFactors = FALSE) %>% 
  filter(constant_vars == "fraction")

astc_in_all <- read.delim("~/Documents/05_results/01_primates/andrew_pipeline/remap_01_2020/astc_events/astc_in_all.txt", header = FALSE, stringsAsFactors = FALSE)


```

```{r load background data}
# compiled in script "remap_background_conservation.Rmd"
load("~/Documents/05_results/01_primates/andrew_pipeline/remap_01_2020/conservation/remap_background_cons.RData")
```

# Three species

## ASTC in all
### skipped exons
```{r make SE top and bottom}
astc_in_all_SE <- astc_in_all %>% 
  filter(str_detect(V1, "SE")) %>% 
  unique()

astc_in_all_SE_top <- all_species_distance %>% 
  filter(event_id %in% astc_in_all_SE$V1) %>% 
  group_by(event_id) %>% 
  mutate(sum_inner_dist=sum(inner_dist)) %>% 
  dplyr::select(event_id, sum_inner_dist) %>% 
  unique() %>% 
  arrange(desc(sum_inner_dist)) %>% 
  head(n=30)

astc_in_all_SE_bottom <- all_species_distance %>% 
  filter(event_id %in% astc_in_all_SE$V1) %>% 
  group_by(event_id) %>% 
  mutate(sum_inner_dist=sum(inner_dist)) %>% 
  dplyr::select(event_id, sum_inner_dist) %>% 
  unique() %>% 
  na.omit() %>% 
  arrange(desc(sum_inner_dist)) %>% 
  tail(n=30)
  
```

```{r get SE scores}
astc_in_all_SE_phastcons <- all_phastcons %>% 
  filter(event_id %in% astc_in_all_SE_top$event_id | event_id %in% astc_in_all_SE_bottom$event_id) %>% 
  mutate(type = case_when(event_id %in% astc_in_all_SE_top$event_id ~ "species-specific",
                          event_id %in% astc_in_all_SE_bottom$event_id ~ "conserved"))

colnames(astc_in_all_SE_phastcons)[10:309] <- c(1:300)
```

```{r make SE plot}
# phastcons with background strict
#png("~/Documents/05_results/01_primates/andrew_pipeline/remap_01_2020/conservation/three_species/astc_in_all_top30_SE_phastcons_w_bg_strict.png", height = 4, width = 12, units = "in", res = 300)
pdf("~/Documents/05_results/01_primates/andrew_pipeline/remap_01_2020/conservation/three_species/astc_in_all_top30_SE_phastcons_w_bg_strict_se.pdf", height = 4, width = 12)
astc_in_all_SE_phastcons %>% 
  gather(position, score, "1":"300") %>% 
  mutate(position = as.numeric(position)) %>% 
  mutate(position_new = case_when(SS == 0 ~ (position-50),
                                 SS == 1 ~ position-250,
                                 SS == 2 ~ position-50,
                                 SS == 3 ~ position-250)) %>% 
  ggplot() +
  geom_ribbon(data = bg_all_three_SE_30_strict, aes(x=position_new, ymin = m-se, ymax= m+se), fill = "grey75") +
  geom_line(data = bg_all_three_SE_30_strict, aes(x=position_new, y=m), color = "black", size=.8) +
  geom_smooth(aes(x=position_new, y=score, group = type, color = type),
              method = "gam", formula = y~s(x)) +
  scale_color_manual(values = c("blue","gold","black"), name="",
                     labels = c("conserved","species-specific","ctrl"), 
                     limits = c("conserved","species-specific","ctrl")) +
  labs(x="Position", y="Conservation (Phastcons)") +
  geom_vline(aes(xintercept = 0), color = "grey") +
  facet_grid(cols = vars(SS), labeller = labeller(SS = labels_SE), scales = "free_x")
dev.off()

  
```

### alternative first exons
```{r make AF top and bottom}
astc_in_all_AF <- astc_in_all %>% 
  filter(str_detect(V1, "AF")) %>% 
  unique()

astc_in_all_AF_top <- all_species_distance %>% 
  filter(event_id %in% astc_in_all_AF$V1) %>% 
  group_by(event_id) %>% 
  mutate(sum_inner_dist=sum(inner_dist)) %>% 
  dplyr::select(event_id, sum_inner_dist) %>% 
  unique() %>% 
  arrange(desc(sum_inner_dist)) %>% 
  head(n=30)

astc_in_all_AF_bottom <- all_species_distance %>% 
  filter(event_id %in% astc_in_all_AF$V1) %>% 
  group_by(event_id) %>% 
  mutate(sum_inner_dist=sum(inner_dist)) %>% 
  dplyr::select(event_id, sum_inner_dist) %>% 
  unique() %>% 
  na.omit() %>% 
  arrange(desc(sum_inner_dist)) %>% 
  tail(n=30)
  
```

```{r get AF scores}
astc_in_all_AF_phastcons <- all_phastcons %>% 
  filter(event_id %in% astc_in_all_AF_top$event_id | event_id %in% astc_in_all_AF_bottom$event_id) %>% 
  mutate(type = case_when(event_id %in% astc_in_all_AF_top$event_id ~ "species-specific",
                          event_id %in% astc_in_all_AF_bottom$event_id ~ "conserved"))

colnames(astc_in_all_AF_phastcons)[10:309] <- c(1:300)


```

```{r make AF plot}
# AF labeller
labels_AF <- c("0" = "Upstream 5'SS", "1" = "Downstream 5'SS", "2" = "3'SS")

# make dataset long first
  
#png("~/Documents/05_results/01_primates/andrew_pipeline/remap_01_2020/conservation/three_species/astc_in_all_top30_AF_phastcons_w_bg_strict.png", height = 4, width = 8, units = "in", res = 300)
pdf("~/Documents/05_results/01_primates/andrew_pipeline/remap_01_2020/conservation/three_species/astc_in_all_top30_AF_phastcons_w_bg_strict_se.pdf", height = 4, width = 8)
astc_in_all_AF_phastcons %>% 
  gather(position, score, "1":"300") %>% 
  mutate(position = as.numeric(position)) %>% 
  mutate(position_new = case_when(SS == 0 ~ position-50,
                                  SS == 1 ~ position-50,
                                  SS == 2 ~ position-250)) %>% 
  group_by(event_id, type, SS) %>% 
  ggplot() +
  geom_ribbon(data = bg_all_three_AF_30_strict, aes(x=position_new, ymin = m-se, ymax= m+se), fill = "grey85") +
  geom_line(data = bg_all_three_AF_30_strict, aes(x=position_new, y=m), color = "black", size=.8) +
  geom_smooth(aes(x=position_new, y=score, group = type, color = type),
              method = "gam", formula = y~s(x)) +
  scale_color_manual(values = c("blue","gold","black"), name="",
                     labels = c("conserved","species-specific","ctrl"), 
                     limits = c("conserved","species-specific","ctrl")) +
  labs(x="Position", y="Conservation (Phastcons)") +
  facet_grid(cols = vars(SS), scales = "free_x", labeller = labeller(SS = labels_AF)) + 
  geom_vline(xintercept=0, color="grey")
dev.off()

  
```

## save
```{r save event list data}
save.image("~/Documents/05_results/01_primates/andrew_pipeline/remap_01_2020/conservation/top_bottom_event_lists_updated.RData")
```

